OUTPUT_DIR="output"
CONDA_EXECUTABLE="conda"
CONDA_ENVIRONMENT="null"
FINETUNED_MODEL="/home/rbossy/code/omnicrobe/text-mining-workflow/ancillaries/re-bert/finetuned_model"
DATA_FILE="input.csv"
REBERT_DIR="/home/rbossy/code/re-bert"
FORCE_CPU="--force_cpu"
PYTHON="python"
